name: Mountainside Tattoo and Piercing
favicon: null
layout_spectrum: 0.779967911541462
typography_spectrum: 0.15014802967198193
title: Mountainside Tattoo and Piercing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#ff0013'
    - '#929292'
    - '#545454'
  brandStrength: 0.8441848340444267
  lightness: 0.6926749716512859
  saturation: 0.44416174991056323
  rhythmicContrast: 0.19783514877781272
purpose: []
