name: Mountainside Tattoo and Piercing
favicon: null
layout_spectrum: 1
typography_spectrum: 0.15014802967198193
title: Mountainside Tattoo and Piercing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ceb884'
    - '#c45c26'
    - '#040707'
    - '#522610'
    - '#5c543d'
  brandStrength: 0.9375
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
