name: Mountainside Tattoo and Piercing
favicon: null
layout_spectrum: 1
typography_spectrum: 0.15014802967198193
title: Mountainside Tattoo and Piercing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#ff0013'
    - '#929292'
    - '#545454'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
